### PR TITLE
Include installing packages in notebook

### PR DESCRIPTION
**Pull request by pjotrp**
We can use mybinder to run the notebook in the workshop. I added the R package installation as run commands. Worked for me.

https://gke.mybinder.org/

### CODE REVIEW

**Comment by kbroman** [comment]
Turns out that I can get the package installs to work by using `devtools::install_github()`. For some reason, `install.packages()` from a private CRAN is not allowed.

_But_ my `qtl2browse::browse()` function doesn't work, because it's supposed to open a browser window and that's not allowed from within the container.

**Comment by pjotrp** [comment]
Well, as long as attendees can follow what you are doing...

**Comment by kbroman** [comment]
I'm inclined to demonstrate things using RStudio rather than the notebook, though.

**Comment by kbroman** [comment]
I think I got RStudio working with binder, and an equivalent Rmd file for those inclined in that direction.

**Pull request merged**
